name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
        build-essential \
        git \
        zip \
        unzip \
        openjdk-17-jdk \
        python3 \
        python3-pip \
        autoconf \
        automake \
        libtool \
        pkg-config \
        gettext \
        autopoint \
        libltdl-dev \
        zlib1g-dev \
        libncurses5 \
        libncurses5-dev \
        libtinfo5 \
        cmake \
        ninja-build

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install cython buildozer

        - name: Prepare Android
          run: |
             mkdir -p ~/.android
             touch ~/.android/repositories.cfg

    - name: Accept Android licenses
      run: |
        yes | sdkmanager --licenses || true

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: future-paski-apk
        path: bin/*.apk
