name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest
      options: --user 1000

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean previous build
        run: rm -rf .buildozer

      - name: Build APK
        run: buildozer android release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
